import os
import json

def create_stitch_project():
    base_dir = r"c:\claude\Saarlekha\stitch_export"
    os.makedirs(base_dir, exist_ok=True)
    
    # 1. project_manifest.json
    manifest = {
      "project_name": "Saarlekha",
      "version": "1.0.0",
      "description": "Multi-tenant internal operations reporting platform for manufacturing companies.",
      "design_system": {
        "name": "Industrial Efficiency System",
        "theme": {
          "primary_color": "#0059bb",
          "secondary_color": "#006a6a",
          "surface_color": "#f9f9ff",
          "on_surface_color": "#181c23",
          "typography": "Inter",
          "style": "Modern corporate, high-contrast, data-dense, hairline borders"
        }
      },
      "core_screens": [
        {
          "id": "SCREEN_AUTH",
          "title": "Auth (Login & Register)",
          "role": "Manual and Google authentication with terms agreement and API configuration."
        },
        {
          "id": "SCREEN_DASHBOARD",
          "title": "Operations Dashboard",
          "role": "Summary KPI cards, production/efficiency summary, and date range filters."
        },
        {
          "id": "SCREEN_DATA_ENTRY",
          "title": "Data Log Entry",
          "role": "Batch data logger with local row queueing and validation."
        },
        {
          "id": "SCREEN_PRODUCTION",
          "title": "Machine Production",
          "role": "Production records, efficiency statistics, and multi-row downloads."
        },
        {
          "id": "SCREEN_QUALITY",
          "title": "Quality Detail Matrix",
          "role": "Loom/operator matrix display with collapsible detail views."
        },
        {
          "id": "SCREEN_MAINTENANCE",
          "title": "Machine Maintenance Log",
          "role": "Log maintenance checklist with custom options and color-coded status badges."
        },
        {
          "id": "SCREEN_JOB_ORDERS",
          "title": "Job Orders Master",
          "role": "Job orders with dynamic custom columns, inline masters quick-creation modals, and selective exports."
        }
      ],
      "technical_stack": "React, TypeScript, Tailwind CSS, HTML5",
      "brand_assets": {
        "primary_logo": "logo.png"
      }
    }
    
    with open(os.path.join(base_dir, "project_manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        
    # 2. export_manifest.md
    manifest_md = """# Saarlekha: Frontend Stitch Export Package

This document contains the consolidated mobile-friendly frontend design system and core screens for Saarlekha.

## 1. Design System (Industrial Efficiency System)

- **Colors:**
  - Primary: `#0059bb` (Industrial Blue) / `#0070ea`
  - Secondary/Accent: `#006a6a` (Precision Teal)
  - Surfaces: `#white` on `#f9f9ff` (Light Gray)
  - Borders: `#c1c6d7` (Hairline Borders)
  - Typography: Inter, with tabular-lining figures (`tnum`) for numeric data.
- **Mobile Paradigm:** Bottom navigation bar, full-screen sheets, cards instead of wide tables, sticky action buttons.

## 2. Core App Screens (Included)

1. **Screen 1: Auth (Login & Register)** [SCREEN_AUTH]
2. **Screen 2: Dashboard Summary** [SCREEN_DASHBOARD]
3. **Screen 3: Data Log Entry** [SCREEN_DATA_ENTRY]
4. **Screen 4: Machine Production** [SCREEN_PRODUCTION]
5. **Screen 5: Quality Detail Matrix** [SCREEN_QUALITY]
6. **Screen 6: Machine Maintenance** [SCREEN_MAINTENANCE]
7. **Screen 7: Job Orders Master** [SCREEN_JOB_ORDERS]

---
*Generated by Google Antigravity for Saarlekha*
"""
    with open(os.path.join(base_dir, "export_manifest.md"), "w", encoding="utf-8") as f:
        f.write(manifest_md)
        
    # Helper function to generate standard HTML shell
    def make_html(title, body_content):
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title} - Saarlekha</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {{
      theme: {{
        extend: {{
          fontFamily: {{
            sans: ['Inter', 'sans-serif'],
          }},
          colors: {{
            primary: {{
              DEFAULT: '#0059bb',
              light: '#0070ea',
            }},
            secondary: {{
              DEFAULT: '#006a6a',
            }},
            surface: '#f9f9ff',
            border: '#c1c6d7',
            text: {{
              primary: '#181c23',
              secondary: '#414754',
            }},
            danger: '#ba1a1a',
            success: '#006a6a',
            pending: '#d97706',
            rejected: '#ba1a1a',
          }},
          borderRadius: {{
            card: '0.75rem',
            input: '0.5rem',
          }}
        }}
      }}
    }}
  </script>
  <style>
    body {{
      font-family: 'Inter', sans-serif;
      -webkit-tap-highlight-color: transparent;
    }}
    .tnum {{
      font-variant-numeric: tabular-nums;
    }}
  </style>
</head>
<body class="bg-surface text-text-primary min-h-screen flex flex-col justify-between">
  
  {body_content}

</body>
</html>
"""

    # 3. SCREEN_AUTH
    auth_content = """
  <div class="flex-1 flex items-center justify-center py-8 px-4">
    <div class="max-w-md w-full bg-white p-6 rounded-card shadow-sm border border-border relative">
      <!-- Settings cog -->
      <button class="absolute top-4 right-4 text-gray-400 hover:text-primary">
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
      </button>

      <div class="text-center mb-6">
        <h2 class="text-2xl font-extrabold text-primary">Saarlekha</h2>
        <p class="text-xs text-text-secondary mt-1">Operations Reporting Platform</p>
      </div>

      <!-- Server Settings Panel (collapsible) -->
      <div class="mb-4 bg-gray-50 p-3 rounded-md border border-border text-xs">
        <div class="font-semibold text-text-primary mb-1">Server Settings</div>
        <div class="text-[10px] text-text-secondary mb-2">Expose local host to tunnel server for testing.</div>
        <div class="flex gap-2">
          <input type="text" value="https://d9ccfb2c54794dcd-106-213-82-255.serveousercontent.com" class="flex-1 border border-border rounded px-2 py-1 focus:outline-none" />
          <button class="bg-primary text-white px-3 py-1 rounded font-medium">Save</button>
        </div>
      </div>

      <!-- Login Form -->
      <form class="space-y-4">
        <div>
          <label class="block text-xs font-medium text-text-primary">Email address</label>
          <input type="email" placeholder="name@company.com" class="mt-1 block w-full border border-border rounded px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary" />
        </div>

        <div>
          <div class="flex justify-between items-center">
            <label class="block text-xs font-medium text-text-primary">Password</label>
            <a href="#" class="text-[10px] text-primary hover:underline">Forgot password?</a>
          </div>
          <input type="password" class="mt-1 block w-full border border-border rounded px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary" />
        </div>

        <!-- Signup checklist (Terms & Conditions) -->
        <div class="flex items-start gap-2">
          <input type="checkbox" id="terms" class="mt-0.5 rounded text-primary focus:ring-primary" />
          <label for="terms" class="text-[10px] text-text-secondary">
            I agree to the <a href="#" class="text-primary underline">Terms &amp; Conditions</a>, <a href="#" class="text-primary underline">Privacy Policy</a>, and <a href="#" class="text-primary underline">Legal Terms</a>.
          </label>
        </div>

        <button type="submit" class="w-full bg-primary hover:bg-primary-light text-white text-sm font-semibold py-2 rounded shadow-sm">
          Sign in
        </button>

        <div class="text-center text-xs text-text-secondary">
          <a href="#" class="text-secondary font-medium hover:underline">Create a new company account</a>
        </div>
      </form>

      <div class="relative my-4">
        <div class="absolute inset-0 flex items-center"><div class="w-full border-t border-border"></div></div>
        <div class="relative flex justify-center text-xs"><span class="bg-white px-2 text-text-secondary">Or continue with</span></div>
      </div>

      <button class="w-full border border-border rounded py-2 flex items-center justify-center text-sm font-medium hover:bg-gray-50">
        <svg class="h-4 w-4 mr-2" viewBox="0 0 24 24"><path fill="#EA4335" d="M12 5.04c1.67 0 3.2.58 4.38 1.69l3.27-3.27C17.67 1.61 14.99 1 12 1 7.35 1 3.39 3.67 1.45 7.56l3.89 3.02c.9-2.73 3.44-4.54 6.66-4.54z"/><path fill="#4285F4" d="M23.49 12.27c0-.81-.07-1.59-.2-2.36H12v4.51h6.46c-.29 1.48-1.14 2.73-2.4 3.58l3.73 2.89c2.18-2.01 3.7-4.99 3.7-8.62z"/><path fill="#FBBC05" d="M5.34 14.61c-.24-.72-.38-1.49-.38-2.29s.14-1.57.38-2.29L1.45 7.02C.52 8.89 0 10.96 0 13.11s.52 4.22 1.45 6.09l3.89-3.59z"/><path fill="#34A853" d="M12 23c3.24 0 5.97-1.07 7.96-2.91l-3.73-2.89c-1.04.7-2.37 1.11-4.23 1.11-3.22 0-5.76-1.81-6.66-4.54L1.45 16.8C3.39 20.33 7.35 23 12 23z"/></svg>
        Sign up with Google
      </button>
    </div>
  </div>
  """
    os.makedirs(os.path.join(base_dir, "screen_1_auth"), exist_ok=True)
    with open(os.path.join(base_dir, "screen_1_auth", "code.html"), "w", encoding="utf-8") as f:
        f.write(make_html("Auth", auth_content))

    # 4. SCREEN_DASHBOARD
    dashboard_content = """
  <!-- Header -->
  <header class="bg-primary text-white px-4 py-3 sticky top-0 z-50 flex items-center justify-between">
    <div class="flex items-center gap-2">
      <span class="font-extrabold text-lg tracking-wide">Saarlekha</span>
      <span class="bg-secondary text-[10px] px-1.5 py-0.5 rounded text-white font-medium uppercase">Crox Oil</span>
    </div>
    <div class="flex items-center gap-3">
      <!-- Date selector -->
      <button class="bg-primary-light text-xs px-2.5 py-1 rounded flex items-center gap-1.5 font-medium border border-blue-400">
        <svg class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 002-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
        <span>Jun 1, 2026</span>
      </button>
    </div>
  </header>

  <!-- Main Body -->
  <main class="flex-1 p-4 space-y-4 pb-20">
    
    <!-- KPI 2x2 Grid for Mobile -->
    <div class="grid grid-cols-2 gap-3">
      
      <!-- Total Production -->
      <div class="bg-white p-3 rounded-card border border-border flex flex-col justify-between shadow-sm">
        <div class="text-[10px] font-semibold text-text-secondary uppercase tracking-wider">Total Production</div>
        <div class="text-xl font-extrabold text-primary mt-1 tnum">14,250 <span class="text-xs font-normal text-text-secondary">mtr</span></div>
        <div class="text-[9px] text-green-600 font-medium mt-1 flex items-center gap-0.5">
          <svg class="h-2.5 w-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 10l7-7m0 0l7 7m-7-7v18"/></svg>
          <span>+4.2% today</span>
        </div>
      </div>
      
      <!-- Avg Efficiency -->
      <div class="bg-white p-3 rounded-card border border-border flex flex-col justify-between shadow-sm">
        <div class="text-[10px] font-semibold text-text-secondary uppercase tracking-wider">Avg Efficiency</div>
        <div class="text-xl font-extrabold text-secondary mt-1 tnum">87.5%</div>
        <div class="text-[9px] text-green-600 font-medium mt-1 flex items-center gap-0.5">
          <svg class="h-2.5 w-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 10l7-7m0 0l7 7m-7-7v18"/></svg>
          <span>+2.1% target</span>
        </div>
      </div>

      <!-- Open Job Orders -->
      <div class="bg-white p-3 rounded-card border border-border flex flex-col justify-between shadow-sm">
        <div class="text-[10px] font-semibold text-text-secondary uppercase tracking-wider">Open Job Orders</div>
        <div class="text-xl font-extrabold text-text-primary mt-1 tnum">12</div>
        <div class="text-[9px] text-amber-600 font-medium mt-1">4 pending delivery</div>
      </div>

      <!-- Active Manpower -->
      <div class="bg-white p-3 rounded-card border border-border flex flex-col justify-between shadow-sm">
        <div class="text-[10px] font-semibold text-text-secondary uppercase tracking-wider">Active Manpower</div>
        <div class="text-xl font-extrabold text-text-primary mt-1 tnum">34 / 40</div>
        <div class="text-[9px] text-text-secondary font-medium mt-1">85% attendance</div>
      </div>

    </div>

    <!-- Machine Maintenance Card -->
    <div class="bg-white rounded-card border border-border p-4 shadow-sm space-y-3">
      <div class="flex justify-between items-center">
        <h3 class="text-xs font-bold uppercase tracking-wider text-text-primary">Machine Maintenance Summary</h3>
        <span class="bg-red-50 text-danger text-[10px] px-1.5 py-0.5 rounded font-bold uppercase">2 critical</span>
      </div>
      
      <!-- List for Mobile -->
      <div class="divide-y divide-border text-xs">
        <div class="py-2.5 flex justify-between items-center">
          <div>
            <div class="font-bold text-text-primary">Loom Machine #04</div>
            <div class="text-[10px] text-text-secondary">Last Maintained: Jun 1, 2026</div>
          </div>
          <span class="bg-teal-50 text-secondary text-[10px] px-2 py-0.5 rounded font-bold uppercase">Completed</span>
        </div>
        <div class="py-2.5 flex justify-between items-center">
          <div>
            <div class="font-bold text-text-primary">Stitch Machine #02</div>
            <div class="text-[10px] text-text-secondary">Last Maintained: May 28, 2026</div>
          </div>
          <span class="bg-red-50 text-danger text-[10px] px-2 py-0.5 rounded font-bold uppercase">Parts Missing</span>
        </div>
        <div class="py-2.5 flex justify-between items-center">
          <div>
            <div class="font-bold text-text-primary">Press Machine #01</div>
            <div class="text-[10px] text-text-secondary">Last Maintained: May 15, 2026</div>
          </div>
          <span class="bg-amber-50 text-amber-600 text-[10px] px-2 py-0.5 rounded font-bold uppercase">Open</span>
        </div>
      </div>
    </div>

    <!-- Operator Efficiency Card -->
    <div class="bg-white rounded-card border border-border p-4 shadow-sm space-y-3">
      <h3 class="text-xs font-bold uppercase tracking-wider text-text-primary">Top Operator Efficiency</h3>
      <div class="space-y-2">
        <div class="flex justify-between text-xs items-center">
          <div class="font-medium text-text-primary">Mudit Garg (Loom)</div>
          <div class="font-bold text-secondary">104.2%</div>
        </div>
        <div class="w-full bg-gray-100 rounded-full h-1.5">
          <div class="bg-secondary h-1.5 rounded-full" style="width: 100%"></div>
        </div>

        <div class="flex justify-between text-xs items-center mt-3">
          <div class="font-medium text-text-primary">Arun Kumar (Stitch)</div>
          <div class="font-bold text-primary">96.5%</div>
        </div>
        <div class="w-full bg-gray-100 rounded-full h-1.5">
          <div class="bg-primary h-1.5 rounded-full" style="width: 96.5%"></div>
        </div>
      </div>
    </div>

  </main>

  <!-- Sticky Bottom Navigation Bar (Tab Bar) -->
  <nav class="bg-white border-t border-border fixed bottom-0 left-0 right-0 z-50 flex items-center justify-around py-2 px-1">
    <a href="#" class="flex flex-col items-center justify-center text-primary gap-0.5">
      <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 24 24"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/></svg>
      <span class="text-[9px] font-bold">Home</span>
    </a>
    <a href="#" class="flex flex-col items-center justify-center text-gray-400 hover:text-primary gap-0.5">
      <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
      <span class="text-[9px] font-medium">Log Entry</span>
    </a>
    <a href="#" class="flex flex-col items-center justify-center text-gray-400 hover:text-primary gap-0.5">
      <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
      <span class="text-[9px] font-medium">Masters</span>
    </a>
  </nav>
  """
    os.makedirs(os.path.join(base_dir, "screen_2_dashboard"), exist_ok=True)
    with open(os.path.join(base_dir, "screen_2_dashboard", "code.html"), "w", encoding="utf-8") as f:
        f.write(make_html("Dashboard", dashboard_content))

    # 5. SCREEN_DATA_ENTRY
    data_entry_content = """
  <!-- Header -->
  <header class="bg-primary text-white px-4 py-3 sticky top-0 z-50 flex items-center gap-3">
    <button class="text-white hover:text-gray-200">
      <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
    </button>
    <h1 class="text-base font-bold">Data Log Entry</h1>
  </header>

  <main class="flex-1 p-4 space-y-4 pb-24">
    <!-- Dropdowns Card -->
    <div class="bg-white p-4 rounded-card border border-border shadow-sm space-y-3">
      <div>
        <label class="block text-xs font-semibold text-text-primary uppercase tracking-wider">Select Format</label>
        <select class="mt-1 block w-full border border-border rounded px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary">
          <option>Daily Quality Report (Weaving)</option>
          <option>Production General Sheet</option>
        </select>
      </div>

      <div>
        <label class="block text-xs font-semibold text-text-primary uppercase tracking-wider">Department</label>
        <select class="mt-1 block w-full border border-border rounded px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary">
          <option>Loom / Weaving</option>
          <option>Stitching & Packing</option>
        </select>
      </div>
    </div>

    <!-- Active Form Entries -->
    <div class="bg-white p-4 rounded-card border border-border shadow-sm space-y-4">
      <div class="font-bold text-xs uppercase tracking-wider text-text-primary border-b border-border pb-1.5 flex justify-between">
        <span>Log Parameters</span>
        <span class="text-primary-light">Format #1.1</span>
      </div>

      <div class="grid grid-cols-2 gap-3 text-xs">
        <div>
          <label class="block font-medium text-text-primary">Loom No.</label>
          <input type="text" class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none" value="Loom #04" />
        </div>
        <div>
          <label class="block font-medium text-text-primary">Operator</label>
          <select class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none bg-white">
            <option>Mudit Garg</option>
            <option>Arun Kumar</option>
          </select>
        </div>
        <div>
          <label class="block font-medium text-text-primary">Recorded Size (mm)</label>
          <input type="number" class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none" value="45.5" />
        </div>
        <div>
          <label class="block font-medium text-text-primary">Required Size (mm)</label>
          <input type="number" class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none" value="45.0" />
        </div>
      </div>

      <button class="w-full bg-secondary hover:bg-teal-700 text-white text-xs font-semibold py-2 rounded flex items-center justify-center gap-1">
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
        Add to Batch Queue
      </button>
    </div>

    <!-- Batch Queue Preview -->
    <div class="bg-white rounded-card border border-border shadow-sm p-4 space-y-2">
      <div class="flex justify-between items-center">
        <h3 class="text-xs font-bold uppercase tracking-wider text-text-primary">Batch Queue (2 rows)</h3>
        <button class="text-danger hover:underline text-[10px] font-bold">Clear All</button>
      </div>

      <!-- Mobile List Cards for Queue -->
      <div class="space-y-2 pt-1 text-xs">
        
        <!-- Row 1 -->
        <div class="bg-surface p-2.5 rounded border border-border flex justify-between items-center">
          <div>
            <div class="font-bold">Loom #04 &bull; Mudit Garg</div>
            <div class="text-[10px] text-text-secondary mt-0.5">Size: 45.5 / Req: 45.0 (Diff: +0.5)</div>
          </div>
          <div class="flex gap-2">
            <button class="text-primary font-semibold hover:underline">Edit</button>
            <button class="text-danger font-semibold hover:underline">Del</button>
          </div>
        </div>

        <!-- Row 2 -->
        <div class="bg-surface p-2.5 rounded border border-border flex justify-between items-center">
          <div>
            <div class="font-bold">Loom #08 &bull; Arun Kumar</div>
            <div class="text-[10px] text-text-secondary mt-0.5">Size: 44.9 / Req: 45.0 (Diff: -0.1)</div>
          </div>
          <div class="flex gap-2">
            <button class="text-primary font-semibold hover:underline">Edit</button>
            <button class="text-danger font-semibold hover:underline">Del</button>
          </div>
        </div>

      </div>
    </div>
  </main>

  <!-- Sticky Bottom Submit Bar -->
  <div class="bg-white border-t border-border fixed bottom-0 left-0 right-0 p-3 z-50 shadow-lg">
    <button class="w-full bg-primary hover:bg-primary-light text-white text-sm font-semibold py-2.5 rounded shadow-sm flex items-center justify-center gap-1.5">
      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      Submit Batch (2 entries)
    </button>
  </div>
  """
    os.makedirs(os.path.join(base_dir, "screen_3_data_entry"), exist_ok=True)
    with open(os.path.join(base_dir, "screen_3_data_entry", "code.html"), "w", encoding="utf-8") as f:
        f.write(make_html("Data Entry", data_entry_content))

    # 6. SCREEN_PRODUCTION
    production_content = """
  <!-- Header -->
  <header class="bg-primary text-white px-4 py-3 sticky top-0 z-50 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <button class="text-white hover:text-gray-200">
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
      </button>
      <h1 class="text-base font-bold">Machine Production</h1>
    </div>
    <div class="flex gap-2 text-xs">
      <button class="bg-secondary px-3 py-1 rounded text-white font-medium flex items-center gap-1.5 shadow-sm">
        <svg class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
        <span>Add Log</span>
      </button>
    </div>
  </header>

  <!-- Export & Search Bar -->
  <div class="bg-white p-3 border-b border-border space-y-2.5">
    <div class="flex gap-2">
      <input type="text" placeholder="Search by machine, operator..." class="flex-1 text-xs border border-border rounded px-3 py-1.5 focus:outline-none" />
      <button class="bg-gray-100 hover:bg-gray-200 text-xs px-3 rounded font-medium border border-border">Filter</button>
    </div>

    <!-- Export Action Bar (Mobile-optimized) -->
    <div class="flex justify-between items-center text-xs">
      <div class="font-medium text-text-secondary">Selected: <span class="font-bold text-primary tnum">2 rows</span></div>
      <div class="flex gap-1.5">
        <button class="bg-primary/5 hover:bg-primary/10 text-primary border border-primary/20 px-2 py-1 rounded text-[10px] font-bold">EXCEL</button>
        <button class="bg-primary/5 hover:bg-primary/10 text-primary border border-primary/20 px-2 py-1 rounded text-[10px] font-bold">PDF</button>
        <button class="bg-primary/5 hover:bg-primary/10 text-primary border border-primary/20 px-2 py-1 rounded text-[10px] font-bold">CSV</button>
      </div>
    </div>
  </div>

  <main class="flex-1 p-4 space-y-3 pb-20">
    
    <!-- Mobile Production Log Cards (Replacing wide tables) -->
    <div class="space-y-3">
      
      <!-- Card 1 -->
      <div class="bg-white rounded-card border border-border p-4 shadow-sm flex items-start gap-3 relative">
        <input type="checkbox" checked class="mt-1 rounded text-primary focus:ring-primary h-4 w-4" />
        
        <div class="flex-1 text-xs space-y-1">
          <div class="flex justify-between items-start">
            <span class="font-bold text-text-primary">Loom Machine #04</span>
            <span class="bg-teal-50 text-secondary px-1.5 py-0.5 rounded font-bold text-[9px]">EFFICIENCY: 104.2%</span>
          </div>
          <div class="text-text-secondary">Operator: <span class="font-semibold text-text-primary">Mudit Garg</span></div>
          <div class="grid grid-cols-2 gap-2 pt-1 text-[11px] tnum">
            <div>Production: <span class="font-bold text-text-primary">5,210 mtr</span></div>
            <div>Daily Target: <span class="font-medium text-text-secondary">5,000 mtr</span></div>
          </div>
          <div class="text-[9px] text-text-secondary pt-1 flex justify-between">
            <span>Date: Jun 1, 2026</span>
            <span>Logged: 18:45</span>
          </div>
        </div>

        <!-- Ellipsis Context Button -->
        <button class="text-gray-400 hover:text-text-primary p-1 absolute top-2 right-2">
          <svg class="h-4 w-4" fill="currentColor" viewBox="0 0 24 24"><path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/></svg>
        </button>
      </div>

      <!-- Card 2 -->
      <div class="bg-white rounded-card border border-border p-4 shadow-sm flex items-start gap-3 relative">
        <input type="checkbox" checked class="mt-1 rounded text-primary focus:ring-primary h-4 w-4" />
        
        <div class="flex-1 text-xs space-y-1">
          <div class="flex justify-between items-start">
            <span class="font-bold text-text-primary">Stitch Machine #02</span>
            <span class="bg-primary/5 text-primary px-1.5 py-0.5 rounded font-bold text-[9px]">EFFICIENCY: 90.0%</span>
          </div>
          <div class="text-text-secondary">Operator: <span class="font-semibold text-text-primary">Arun Kumar</span></div>
          <div class="grid grid-cols-2 gap-2 pt-1 text-[11px] tnum">
            <div>Production: <span class="font-bold text-text-primary">1,800 pcs</span></div>
            <div>Daily Target: <span class="font-medium text-text-secondary">2,000 pcs</span></div>
          </div>
          <div class="text-[9px] text-text-secondary pt-1 flex justify-between">
            <span>Date: Jun 1, 2026</span>
            <span>Logged: 18:32</span>
          </div>
        </div>

        <button class="text-gray-400 hover:text-text-primary p-1 absolute top-2 right-2">
          <svg class="h-4 w-4" fill="currentColor" viewBox="0 0 24 24"><path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/></svg>
        </button>
      </div>

    </div>

  </main>
  """
    os.makedirs(os.path.join(base_dir, "screen_4_production"), exist_ok=True)
    with open(os.path.join(base_dir, "screen_4_production", "code.html"), "w", encoding="utf-8") as f:
        f.write(make_html("Machine Production", production_content))

    # 7. SCREEN_QUALITY
    quality_content = """
  <!-- Header -->
  <header class="bg-primary text-white px-4 py-3 sticky top-0 z-50 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <button class="text-white hover:text-gray-200">
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
      </button>
      <h1 class="text-base font-bold">Daily Quality Report</h1>
    </div>
  </header>

  <!-- Segmented Control Filters -->
  <div class="bg-white p-3 border-b border-border space-y-3">
    <div class="bg-gray-100 p-0.5 rounded-lg flex text-xs">
      <button class="flex-1 bg-white text-primary font-bold py-1.5 rounded-md shadow-sm">Machine-wise</button>
      <button class="flex-1 text-text-secondary py-1.5 font-medium">Operator-wise</button>
    </div>
    
    <div class="flex justify-between items-center text-xs">
      <div class="text-text-secondary font-medium">Total Machines: <span class="font-bold text-text-primary tnum">2</span></div>
      <div class="flex gap-2">
        <button class="text-primary font-semibold hover:underline">Expand All</button>
        <span class="text-gray-300">|</span>
        <button class="text-primary font-semibold hover:underline">Collapse All</button>
      </div>
    </div>
  </div>

  <main class="flex-1 p-4 space-y-3 pb-20">
    
    <!-- Collapsible Accordion Grid Cards -->
    <div class="space-y-3">
      
      <!-- Accordion #1: Expanded -->
      <div class="bg-white rounded-card border border-border shadow-sm overflow-hidden">
        <!-- Accordion Header -->
        <button class="w-full flex justify-between items-center px-4 py-3 bg-gray-50 border-b border-border text-xs font-bold text-text-primary">
          <div class="flex items-center gap-1.5">
            <svg class="h-4 w-4 text-secondary" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/></svg>
            <span>Loom Machine #04</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[10px] text-text-secondary">2 entries</span>
            <svg class="h-4 w-4 text-text-secondary transition-transform transform rotate-180" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
          </div>
        </button>

        <!-- Accordion Content -->
        <div class="p-3 divide-y divide-border text-[11px]">
          
          <!-- Entry 1 -->
          <div class="py-2.5 space-y-1">
            <div class="flex justify-between font-bold text-text-primary">
              <span>Loom No: #04 &bull; Mudit Garg</span>
              <span class="text-primary font-bold">18:45</span>
            </div>
            <div class="grid grid-cols-2 gap-2 text-text-secondary tnum">
              <div>Required Size: <span class="font-semibold text-text-primary">45.0 mm</span></div>
              <div>Recorded Size: <span class="font-semibold text-text-primary">45.5 mm</span></div>
              <div>Variation: <span class="text-danger font-bold">+0.5 mm</span></div>
              <div>Loom Quality: <span class="text-secondary font-bold">Grade-A</span></div>
            </div>
          </div>

          <!-- Entry 2 -->
          <div class="py-2.5 space-y-1">
            <div class="flex justify-between font-bold text-text-primary">
              <span>Loom No: #04 &bull; Arun Kumar</span>
              <span class="text-primary font-bold">16:15</span>
            </div>
            <div class="grid grid-cols-2 gap-2 text-text-secondary tnum">
              <div>Required Size: <span class="font-semibold text-text-primary">45.0 mm</span></div>
              <div>Recorded Size: <span class="font-semibold text-text-primary">44.8 mm</span></div>
              <div>Variation: <span class="text-danger font-bold">-0.2 mm</span></div>
              <div>Loom Quality: <span class="text-secondary font-bold">Grade-A</span></div>
            </div>
          </div>

        </div>
      </div>

      <!-- Accordion #2: Collapsed -->
      <div class="bg-white rounded-card border border-border shadow-sm overflow-hidden">
        <button class="w-full flex justify-between items-center px-4 py-3 bg-gray-50 text-xs font-bold text-text-primary">
          <div class="flex items-center gap-1.5">
            <svg class="h-4 w-4 text-secondary" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/></svg>
            <span>Loom Machine #08</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[10px] text-text-secondary">0 entries</span>
            <svg class="h-4 w-4 text-text-secondary transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
          </div>
        </button>
      </div>

    </div>

  </main>
  """
    os.makedirs(os.path.join(base_dir, "screen_5_quality"), exist_ok=True)
    with open(os.path.join(base_dir, "screen_5_quality", "code.html"), "w", encoding="utf-8") as f:
        f.write(make_html("Daily Quality Matrix", quality_content))

    # 8. SCREEN_MAINTENANCE
    maintenance_content = """
  <!-- Header -->
  <header class="bg-primary text-white px-4 py-3 sticky top-0 z-50 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <button class="text-white hover:text-gray-200">
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
      </button>
      <h1 class="text-base font-bold">Log Maintenance</h1>
    </div>
  </header>

  <main class="flex-1 p-4 space-y-4 pb-20">
    
    <!-- Maintenance Details Card -->
    <div class="bg-white p-4 rounded-card border border-border shadow-sm space-y-3">
      <div class="grid grid-cols-2 gap-3 text-xs">
        <div>
          <label class="block font-semibold text-text-primary uppercase tracking-wider">Select Machine</label>
          <select class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none bg-white">
            <option>Loom Machine #04</option>
            <option>Stitch Machine #02</option>
          </select>
        </div>
        <div>
          <label class="block font-semibold text-text-primary uppercase tracking-wider">Maintenance Type</label>
          <select class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none bg-white">
            <option>Preventative</option>
            <option>Breakdown Repair</option>
          </select>
        </div>
      </div>
      
      <div class="text-xs">
        <label class="block font-semibold text-text-primary uppercase tracking-wider">Status</label>
        <div class="grid grid-cols-4 gap-1.5 mt-1">
          <button class="bg-teal-50 text-secondary border border-secondary px-2 py-1.5 rounded text-[10px] font-bold uppercase text-center">Completed</button>
          <button class="bg-white text-text-secondary border border-border px-2 py-1.5 rounded text-[10px] font-bold uppercase text-center">Open</button>
          <button class="bg-white text-text-secondary border border-border px-2 py-1.5 rounded text-[10px] font-bold uppercase text-center">In Progress</button>
          <button class="bg-white text-text-secondary border border-border px-2 py-1.5 rounded text-[10px] font-bold uppercase text-center">Parts Missing</button>
        </div>
      </div>
    </div>

    <!-- Dynamic Checklist -->
    <div class="bg-white p-4 rounded-card border border-border shadow-sm space-y-3">
      <div class="font-bold text-xs uppercase tracking-wider text-text-primary border-b border-border pb-1.5">
        Custom Checklist Items
      </div>

      <div class="space-y-3 text-xs pt-1">
        
        <!-- Checklist 1 -->
        <div class="flex items-start gap-2.5">
          <input type="checkbox" id="item1" class="mt-0.5 rounded text-primary focus:ring-primary h-4 w-4" checked />
          <div>
            <label for="item1" class="font-bold text-text-primary">Lubricated Gears</label>
            <div class="text-[10px] text-text-secondary">Ensure grease levels are within safe parameters.</div>
          </div>
        </div>

        <!-- Checklist 2 -->
        <div class="flex items-start gap-2.5">
          <input type="checkbox" id="item2" class="mt-0.5 rounded text-primary focus:ring-primary h-4 w-4" checked />
          <div>
            <label for="item2" class="font-bold text-text-primary">Calibrated Sensor Scales</label>
            <div class="text-[10px] text-text-secondary">Align variation tolerance bounds.</div>
          </div>
        </div>

        <!-- Checklist 3 -->
        <div class="flex items-start gap-2.5">
          <input type="checkbox" id="item3" class="mt-0.5 rounded text-primary focus:ring-primary h-4 w-4" />
          <div>
            <label for="item3" class="font-bold text-text-primary">Inspected Safety Guards</label>
            <div class="text-[10px] text-text-secondary">Confirm manual override lock remains active.</div>
          </div>
        </div>

      </div>
    </div>

  </main>

  <!-- Sticky Bottom Log Entry Bar -->
  <div class="bg-white border-t border-border fixed bottom-0 left-0 right-0 p-3 z-50">
    <button class="w-full bg-primary hover:bg-primary-light text-white text-sm font-semibold py-2.5 rounded shadow-sm flex items-center justify-center gap-1.5">
      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/></svg>
      Save Maintenance Activity
    </button>
  </div>
  """
    os.makedirs(os.path.join(base_dir, "screen_6_maintenance"), exist_ok=True)
    with open(os.path.join(base_dir, "screen_6_maintenance", "code.html"), "w", encoding="utf-8") as f:
        f.write(make_html("Log Maintenance", maintenance_content))

    # 9. SCREEN_JOB_ORDERS
    job_orders_content = """
  <!-- Header -->
  <header class="bg-primary text-white px-4 py-3 sticky top-0 z-50 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <button class="text-white hover:text-gray-200">
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
      </button>
      <h1 class="text-base font-bold">Job Orders Master</h1>
    </div>
    <button class="text-white hover:text-gray-200">
      <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
    </button>
  </header>

  <!-- Quick creation form (Inline link overlays) -->
  <div class="bg-white p-4 border-b border-border shadow-sm text-xs space-y-3">
    <div class="font-bold uppercase tracking-wider text-text-primary flex justify-between items-center">
      <span>Create Job Order</span>
      <div class="flex gap-2">
        <a href="#" class="text-primary hover:underline font-bold">+ New Customer</a>
        <span class="text-gray-300">|</span>
        <a href="#" class="text-primary hover:underline font-bold">+ New Item</a>
      </div>
    </div>

    <!-- Inputs -->
    <div class="grid grid-cols-2 gap-3">
      <div>
        <label class="block font-medium text-text-primary">Select Customer</label>
        <select class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none bg-white">
          <option>Crox Oil and Gas</option>
          <option>Garg Industries</option>
        </select>
      </div>

      <div>
        <label class="block font-medium text-text-primary">Order Quantity</label>
        <input type="number" placeholder="e.g. 5000" class="mt-1 block w-full border border-border rounded px-2.5 py-1.5 focus:outline-none tnum" />
      </div>
    </div>
  </div>

  <!-- Job Orders List -->
  <main class="flex-1 p-4 space-y-3 pb-20">
    <div class="space-y-3">
      
      <!-- Job Card 1 -->
      <div class="bg-white rounded-card border border-border p-4 shadow-sm relative text-xs space-y-2">
        <div class="flex justify-between items-center border-b border-border pb-1.5">
          <div class="font-bold text-primary">JOB-2026-001</div>
          <span class="bg-teal-50 text-secondary px-2 py-0.5 rounded font-bold text-[9px] uppercase">Active</span>
        </div>
        <div class="space-y-1">
          <div class="text-text-secondary">Customer: <span class="font-semibold text-text-primary">Crox Oil and Gas</span></div>
          <div class="text-text-secondary">Item Description: <span class="font-semibold text-text-primary">Standard Loom Bag v3</span></div>
          
          <div class="grid grid-cols-2 gap-2 pt-1 text-[11px] tnum">
            <div>Order Qty: <span class="font-bold text-text-primary">10,000 pcs</span></div>
            <div>Production Qty: <span class="font-medium text-text-secondary">5,200 pcs</span></div>
          </div>
        </div>
        
        <div class="flex gap-2 justify-end pt-2 border-t border-border mt-1">
          <button class="text-primary font-bold hover:underline">Edit Details</button>
          <button class="text-danger font-bold hover:underline">Close Order</button>
        </div>
      </div>

    </div>
  </main>
  """
    os.makedirs(os.path.join(base_dir, "screen_7_job_orders"), exist_ok=True)
    with open(os.path.join(base_dir, "screen_7_job_orders", "code.html"), "w", encoding="utf-8") as f:
        f.write(make_html("Job Orders Master", job_orders_content))
        
    print(f"Stitch project files generated successfully at {base_dir}")

if __name__ == "__main__":
    create_stitch_project()
